apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "123456"
    ports:
      - containerPort: 3306
    volumeMounts:
      - mountPath: /var/lib/mysql # 容器中的目录
        name: data-volume

  volumes:
    - name: data-volume
      hostPath:
        # 宿主机上目录位置
        path: /home/mysql/data
        type: DirectoryOrCreate
